import React from 'react';
import { hydrateRoot } from 'react-dom/client';
import App from './App';
import type { PageData } from './types';
import '@fontsource/ibm-plex-sans/latin-400.css';
import '@fontsource/ibm-plex-sans/latin-500.css';
import '@fontsource/ibm-plex-sans/latin-600.css';
import '@fontsource/ibm-plex-serif/latin-400.css';
import '@fontsource/ibm-plex-mono/latin-400.css';
import '@fontsource/noto-sans-sc/400.css';
import '@fontsource/noto-sans-sc/500.css';
import './styles.css';
const data = JSON.parse(document.getElementById('atlas-data')!.textContent!) as PageData;
hydrateRoot(document.getElementById('root')!, <App data={data} />);
